= gradle-linkchecker-plugin

The `gradle-linkchecker-plugin` is a Gradle plugin to check links in a given HTML file.
Non-URL links (i.e. local files) will be added for further link checking.

This plugin will crawl the links (`a`, `frame`, and `img`) in local HTML files.
It will validate all links to go out to real files or web locations.
It will stop there, and not crawl the whole Internet!
It was originally designed to validate the links between help documents in HTML, that pointed to each other, to local image files, and to some web locations.

This plugin does not require dynamic content, rather just a directory with an HTML file to start from (`inputDir`) and it only has a single task, `checklinks`.

This Gradle plugin is based on a https://github.com/JamaSoftwareEngineering/linkchecker-maven-plugin[Maven plugin].
We acknowledge and are grateful to these developers for their contributions to open source.
You can find the source code of their original using the link above.
This new version was created with https://github.com/JamaSoftwareEngineering/linkchecker-maven-plugin/issues/1[their consent].

== Using The Plugin

See this plugin's page in the
https://plugins.gradle.org/plugin/org.openrepose.gradle.plugins.linkchecker[gradle plugins repo].

== Plugin Conventions

The `linkchecker` convention defines the conventions for this entire plugin.

You can change the defaults with a closure in your build script.

[source, groovy]
----
linkchecker {
  ...
}
----

=== Link Checker Plugin Convention

These are the configurable parameters for the Link Checker Plugin.
If the **Default** is **none**, then the parameter is **NOT** optional and a value must be provided.

.Link Checker Plugin Parameters
[cols="2,6,3,2"]
|===
| Parameter
| Description
| Default
| Type

| `inputDir`
| The directory that will be used for UP-TO-DATE checks.
  Links from the file will be checked.
  Non-URL links (i.e. local files) will be taken for further link checking (feels like recursion).
| **none**
| `File`

| `defaultFile`
| The file name to be used as the default, in case a (non-URL) link points to a folder.
  It's what happens on a web server: requests for `http://foo/bar` will serve you (typically) `http://foo/bar/index.html`.
| `index.html`
| `String`

| `startFile`
| The file to start from.
  If this file is not absolute, then it is assumed to be relative to the `inputDir`.
  Links from the file will be checked.
  Non-URL links (i.e. local files) will be taken for further link checking (feels like recursion).
| `index.html`
| `File`

| `failOnLocalHost`
| Should this plugin make your build fail if it encounters links to `localhost`.
  Typically, depending on something local to the build would hamper the portability of the build.
| `true`
| `Boolean`

| `failOnIgnoreHost`
| Should this plugin make your build fail if it encounters links to an ignored host.
  Typically only enabled if there are troublesome links that would normally require multi-party authentication to access (e.g. SAML, OAuth).
| `false`
| `Boolean`

| `failOnBadUrls`
| Should this plugin make your build fail if it encounters bad URLs.
  This is not the default, in appreciation of the fact that (non-local) URLs are out of our control.
  Typically, validating (non-local) URLs would hamper the reproducibility of the build.
| `false`
| `Boolean`

| `httpURLConnectionTimeout`
| Sets a specified timeout value, in milliseconds, to be used when opening a communications link to a non-local URL.
  A timeout of zero is interpreted as an infinite timeout.
  A timeout of less than zero is interpreted to use the system timeout.
| `-1`
| `int`

| `ignoreHostRegexs`
| A list of regular expressions of hosts to not even attempt communications with.
| empty `List`
| `Collection<String>`

| `reportOnly`
| Should this plugin make your build fail altogether, or only report its findings.
| `false`
| `Boolean`

| `logFile`
| This is the file where results are logged.
| `$buildDir/reports/linkchecker.txt`
| `File`
|===

== Examples

=== Basic Example

If the default conventions don't need to be modified, then the only thing to configure is the `inputDir`.

[source, groovy]
----
linkchecker {
  inputDir = new File("$buildDir/asciidoc/html5/")
}
----

=== Complete Example explicitly stating the `defaults`

This is equivalent to the Basic Example above.
This one just explicitly states the defaults in addition to configuring the `startFile`.

[source, groovy]
----
linkchecker {
  inputDir                 = new File("$buildDir/asciidoc/html5/")
  defaultFile              = index.html
  startFile                = new File("index.html")
  failOnLocalHost          = true
  failOnIgnoreHost         = false
  failOnBadUrls            = false
  httpURLConnectionTimeout = -1
  ignoreHostRegexs         = []
  reportOnly               = false
  logFile                  = new File("$buildDir/reports/linkchecker.txt")
}
----

=== Real World Example

For a real world example of this plugin, please visit the main https://github.com/rackerlabs/repose[Repose project] and take a look at our https://github.com/rackerlabs/repose/blob/master/build.gradle[build file].

== Similar Projects
The https://github.com/aim42/htmlSanityCheck[HtmlSanityChecker] is an
(open source) gradle plugin to check HTML files for any kinds of
issues, e.g. missing images, broken cross-references etc.
It creates a JUnit-like report and might be a complement
to this `gradle-linkchecker-plugin`.


== License

This project is licensed under https://www.apache.org/licenses/LICENSE-2.0.txt[the Apache License, Version 2.0].

== Improvements

If you have an idea that would make something a little easier, we'd love to hear about it.
If you think you can make this plugin better, then simply fork it and submit a pull request.
